package delivery

import "github.com/rhine-tech/scene/lens/authentication"

type UserNoPassword struct {
	// UserID unique id. should be generated by server.
	UserID string `json:"user_id" bson:"user_id" gorm:"primaryKey"`
	// Username unique name. should be unique. should be input by user. but can be changed
	Username string `json:"username" bson:"username" gorm:"uniqueIndex"`
	// Email user's email address
	Email string `json:"email" bson:"email"`
	// DisplayName extra information, can be empty
	DisplayName string `json:"display_name" bson:"display_name"`
	// Avatar extra information, can be empty
	Avatar string `json:"avatar" bson:"avatar"`
	// Timezone extra information, can be empty
	Timezone string `json:"timezone" bson:"timezone"`
}

func (v UserNoPassword) FromUser(u authentication.User) UserNoPassword {
	return UserNoPassword{
		UserID:      u.UserID,
		Username:    u.Username,
		Email:       u.Email,
		DisplayName: u.DisplayName,
		Avatar:      u.Avatar,
		Timezone:    u.Timezone,
	}
}
